"""Initial

Revision ID: 601a1425edee
Revises: 35d31c24f41d
Create Date: 2025-07-12 22:18:04.391426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601a1425edee'
down_revision = '35d31c24f41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
