"""ad

Revision ID: 851b1721f583
Revises: cc8dcc7e7d51
Create Date: 2025-07-10 00:30:25.772773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851b1721f583'
down_revision = 'cc8dcc7e7d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_key', sa.String(length=64), nullable=False))
        batch_op.drop_column('topic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('roadmap_key')

    # ### end Alembic commands ###
