"""Add roadmap_key to BlogPost

Revision ID: cc8dcc7e7d51
Revises: 8ae85f3a6d1a
Create Date: 2025-07-08 23:11:05.748407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8dcc7e7d51'
down_revision = '8ae85f3a6d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('goal_posts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('roadmap_key')

    op.drop_table('roadmap_items')
    # ### end Alembic commands ###
